services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: poc_db
    ports:
      - "5432:5432"
    volumes:
      # Windows
      #- J:/Storage/postgres_data:/var/lib/postgresql/data
      # Mac
      - /Volumes/T7/Storage/postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: alvin_azurin@yahoo.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    volumes:
      # Windows
      # - J:/Storage/pgadmin_data:/var/lib/pgadmin
      - /Volumes/T7/Storage/pgadmin_data:/var/lib/pgadmin
volumes:
  postgres_data:
    driver: local
  pgadmin_data:
    driver: local